Config = {}

Config.Debug = false
Config.FrameworkResource = 'vorp_core'
Config.InventoryApiResource = 'vorp_inventory' -- Ustaw na nazwe inventory resource u ciebie, np. 'vorp_inventory' albo 'vorp_inventoryApi'
Config.InventoryFallbackResources = { 'vorp_inventory', 'vorp_inventoryApi' }
Config.DefaultSkillPointsPerLevel = 1
Config.CraftingDurationMs = 5000
Config.ProgressTickMs = 250
Config.BlueprintItemPrefix = 'blueprint_'
Config.DefaultCategory = 'general'
Config.BlueprintPointCost = 1
Config.BlueprintOpenCommand = 'blueprints'

Config.XpByCategory = {
    weapon = 40,
    medicine = 25,
    food = 20,
    utility = 15,
    survival = 25,
    general = 10,
}

Config.SkillTree = {
    survival = {
        label = 'Survival',
        description = 'Bronie survivalowe, luki i camp crafting.',
        maxLevel = 5,
    },
    medicine = {
        label = 'Medicine',
        description = 'Toniki, bandaze i przedmioty lecznicze.',
        maxLevel = 5,
    },
    gunsmith = {
        label = 'Gunsmith',
        description = 'Amunicja, rewolwery i bron palna.',
        maxLevel = 5,
    },
    blacksmith = {
        label = 'Blacksmith',
        description = 'Maczety, narzedzia i ciezszy crafting.',
        maxLevel = 5,
    },
}

Config.CraftingStations = {
    campfire = {
        label = 'Survival Crafting Table',
        subtitle = 'Cooking & Bows',
        theme = 'survival',
        coords = vector3(-372.15, 796.24, 116.18),
        radius = 2.0,
        categories = {
            {
                key = 'food',
                label = 'Cooking',
                description = 'Jedzenie i obozowe przepisy przy ogniu.',
                icon = '🥩',
            },
            {
                key = 'bows',
                label = 'Bows',
                description = 'Luki, strzaly i pociski survivalowe.',
                icon = '🏹',
            },
            {
                key = 'medicine',
                label = 'Medicine',
                description = 'Bandaze i podstawowe lekarstwa.',
                icon = '🩹',
            },
        },
    },
    workbench = {
        label = 'Weapons Crafting Table',
        subtitle = 'Revolvers & Repeaters',
        theme = 'gunsmith',
        coords = vector3(-276.84, 778.91, 119.51),
        radius = 2.0,
        categories = {
            {
                key = 'revolvers',
                label = 'Revolvers',
                description = 'Klasyczne rewolwery i bron krotka.',
                icon = '🔫',
            },
            {
                key = 'repeaters',
                label = 'Repeaters',
                description = 'Powtarzalne karabiny i bron dalekiego zasiegu.',
                icon = '🪖',
            },
            {
                key = 'ammo',
                label = 'Ammo',
                description = 'Amunicja do broni palnej.',
                icon = '💥',
            },
        },
    },
    blacksmith = {
        label = 'Blacksmith Crafting Table',
        subtitle = 'Metal Works',
        theme = 'blacksmith',
        coords = vector3(-1815.12, -403.87, 160.38),
        radius = 2.0,
        categories = {
            {
                key = 'metalwork',
                label = 'Metal Works',
                description = 'Ciezsze ostrza i narzedzia kowalskie.',
                icon = '⚒️',
            },
            {
                key = 'tools',
                label = 'Tools',
                description = 'Latarnie, pochodnie i narzedzia.',
                icon = '🛠️',
            },
        },
    },
}

Config.Recipes = {
    cooked_meat = {
        label = 'Cooked Meat',
        description = 'Swiezo przyprawione mieso przygotowane nad ogniem.',
        station = 'campfire',
        category = 'food',
        theme = 'survival',
        craftTimeMs = 4000,
        durationLabel = '00:40',
        icon = '🥩',
        previewModel = 'p_cookedmeat01x',
        blueprint = 'camp_cooking_1',
        skillRequirements = { survival = 1 },
        ingredients = {
            { item = 'meat', label = 'Meat', count = 2 },
            { item = 'salt', label = 'Salt', count = 2 },
        },
        rewards = {
            { item = 'cooked_meat', count = 1 },
        },
        xp = 20,
        blueprintNode = 'camp_cooking_1',
    },
    arrow = {
        label = 'Arrow',
        description = 'Lekkie strzaly z drewna i pior.',
        station = 'campfire',
        category = 'bows',
        theme = 'survival',
        craftTimeMs = 3500,
        durationLabel = '00:35',
        icon = '🏹',
        previewModel = 'p_arrowbundle01x',
        blueprint = 'arrow_kit',
        skillRequirements = { survival = 2 },
        ingredients = {
            { item = 'feather', label = 'Feather', count = 2 },
            { item = 'wood', label = 'Wood', count = 1 },
        },
        rewards = {
            { item = 'ammoarrow', count = 10 },
        },
        xp = 25,
        blueprintNode = 'arrow_kit',
    },
    bandage = {
        label = 'Bandage',
        description = 'Podstawowy opatrunek do leczenia ran.',
        station = 'campfire',
        category = 'medicine',
        theme = 'medicine',
        craftTimeMs = 3000,
        durationLabel = '00:30',
        icon = '🩹',
        blueprint = 'basic_medicine',
        skillRequirements = { medicine = 1 },
        ingredients = {
            { item = 'cloth', label = 'Cloth', count = 2 },
            { item = 'alcohol', label = 'Alcohol', count = 1 },
        },
        rewards = {
            { item = 'bandage', count = 1 },
        },
        xp = 20,
        blueprintNode = 'basic_medicine',
    },
    snake_oil = {
        label = 'Snake Oil',
        description = 'Tonik przywracajacy energie i skupienie.',
        station = 'campfire',
        category = 'medicine',
        theme = 'medicine',
        craftTimeMs = 5000,
        durationLabel = '00:50',
        icon = '🧪',
        blueprint = 'snake_oil',
        skillRequirements = { medicine = 2 },
        ingredients = {
            { item = 'sage', label = 'Sage', count = 2 },
            { item = 'ginseng', label = 'Ginseng', count = 1 },
            { item = 'water', label = 'Water', count = 1 },
        },
        rewards = {
            { item = 'snake_oil', count = 1 },
        },
        xp = 35,
        blueprintNode = 'snake_oil',
    },
    cattleman_revolver = {
        label = 'Cattleman Revolver',
        description = 'Klasyczny single-action rewolwer Dzikiego Zachodu.',
        station = 'workbench',
        category = 'revolvers',
        theme = 'gunsmith',
        craftTimeMs = 6000,
        durationLabel = '01:00',
        icon = '🔫',
        blueprint = 'cattleman_revolver',
        skillRequirements = { gunsmith = 2 },
        ingredients = {
            { item = 'iron', label = 'Iron', count = 20 },
            { item = 'copper', label = 'Copper', count = 10 },
            { item = 'wood', label = 'Wood', count = 5 },
        },
        rewards = {
            { item = 'weapon_revolver_cattleman', count = 1 },
        },
        xp = 50,
        blueprintNode = 'cattleman_revolver',
    },
    double_action_revolver = {
        label = 'Double Action Revolver',
        description = 'Szybkostrzelnny rewolwer do walki na bliski dystans.',
        station = 'workbench',
        category = 'revolvers',
        theme = 'gunsmith',
        craftTimeMs = 6500,
        durationLabel = '01:05',
        icon = '🔫',
        blueprint = 'double_action_revolver',
        skillRequirements = { gunsmith = 3 },
        ingredients = {
            { item = 'iron', label = 'Iron', count = 20 },
            { item = 'copper', label = 'Copper', count = 20 },
            { item = 'wood', label = 'Wood', count = 5 },
        },
        rewards = {
            { item = 'weapon_revolver_doubleaction', count = 1 },
        },
        xp = 60,
        blueprintNode = 'double_action_revolver',
    },
    carbine_repeater = {
        label = 'Carbine Repeater',
        description = 'Lekki i wszechstronny karabin typu repeater.',
        station = 'workbench',
        category = 'repeaters',
        theme = 'gunsmith',
        craftTimeMs = 8000,
        durationLabel = '01:20',
        icon = '🪖',
        blueprint = 'carbine_repeater',
        skillRequirements = { gunsmith = 4 },
        ingredients = {
            { item = 'iron', label = 'Iron', count = 20 },
            { item = 'copper', label = 'Copper', count = 25 },
            { item = 'hardwood', label = 'Hard Wood', count = 10 },
        },
        rewards = {
            { item = 'weapon_repeater_carbine', count = 1 },
        },
        xp = 75,
        blueprintNode = 'carbine_repeater',
    },
    revolver_ammo = {
        label = 'Revolver Ammo',
        description = 'Standardowa amunicja do rewolwerow.',
        station = 'workbench',
        category = 'ammo',
        theme = 'gunsmith',
        craftTimeMs = 3000,
        durationLabel = '00:30',
        icon = '💥',
        blueprint = 'revolver_ammo',
        skillRequirements = { gunsmith = 2 },
        ingredients = {
            { item = 'metal_scrap', label = 'Metal Scrap', count = 2 },
            { item = 'gunpowder', label = 'Gunpowder', count = 1 },
        },
        rewards = {
            { item = 'ammorevolvernormal', count = 12 },
        },
        xp = 40,
        blueprintNode = 'revolver_ammo',
    },
    machete = {
        label = 'Machete',
        description = 'Ciezkie ostrze do przecinania krzakow i walki.',
        station = 'blacksmith',
        category = 'metalwork',
        theme = 'blacksmith',
        craftTimeMs = 4000,
        durationLabel = '00:40',
        icon = '⚔️',
        blueprint = 'machete',
        skillRequirements = { blacksmith = 2 },
        ingredients = {
            { item = 'iron', label = 'Iron', count = 20 },
        },
        rewards = {
            { item = 'weapon_melee_machete', count = 1 },
        },
        xp = 35,
        blueprintNode = 'machete',
    },
}

Config.BlueprintTree = {
    {
        key = 'revolvers_t1',
        label = 'Revolvers I',
        description = 'Podstawowe rewolwery i obsluga krotszej broni.',
        group = 'Revolvers',
        tier = 1,
        position = { x = 8, y = 10 },
        skill = 'gunsmith',
        cost = 1,
        recipeKeys = { 'cattleman_revolver' },
    },
    {
        key = 'revolvers_t2',
        label = 'Revolvers II',
        description = 'Szybsze rewolwery i bron premium.',
        group = 'Revolvers',
        tier = 2,
        position = { x = 32, y = 10 },
        skill = 'gunsmith',
        cost = 2,
        requires = { 'revolvers_t1' },
        recipeKeys = { 'double_action_revolver' },
    },
    {
        key = 'repeaters_t1',
        label = 'Repeaters I',
        description = 'Wejscie w karabiny powtarzalne.',
        group = 'Repeaters',
        tier = 3,
        position = { x = 56, y = 28 },
        skill = 'gunsmith',
        cost = 2,
        requires = { 'revolvers_t2' },
        recipeKeys = { 'carbine_repeater' },
    },
    {
        key = 'ammo_t1',
        label = 'Ammo Research',
        description = 'Receptury na podstawowa amunicje.',
        group = 'Ammo',
        tier = 2,
        position = { x = 56, y = 10 },
        skill = 'gunsmith',
        cost = 1,
        requires = { 'revolvers_t1' },
        recipeKeys = { 'revolver_ammo' },
    },
    {
        key = 'camp_cooking_1',
        label = 'Camp Cooking',
        description = 'Jedzenie i gotowanie przy ognisku.',
        group = 'Survival',
        tier = 1,
        position = { x = 8, y = 52 },
        skill = 'survival',
        cost = 1,
        recipeKeys = { 'cooked_meat' },
    },
    {
        key = 'arrow_kit',
        label = 'Arrow Craft',
        description = 'Strzaly i lekki crafting lowiecki.',
        group = 'Survival',
        tier = 2,
        position = { x = 32, y = 52 },
        skill = 'survival',
        cost = 1,
        requires = { 'camp_cooking_1' },
        recipeKeys = { 'arrow' },
    },
    {
        key = 'basic_medicine',
        label = 'Field Medicine',
        description = 'Bandaze i podstawowe leczenie w terenie.',
        group = 'Medicine',
        tier = 1,
        position = { x = 8, y = 76 },
        skill = 'medicine',
        cost = 1,
        recipeKeys = { 'bandage' },
    },
    {
        key = 'snake_oil',
        label = 'Snake Oil',
        description = 'Lepszy tonik i mocniejsze mikstury.',
        group = 'Medicine',
        tier = 2,
        position = { x = 32, y = 76 },
        skill = 'medicine',
        cost = 1,
        requires = { 'basic_medicine' },
        recipeKeys = { 'snake_oil' },
    },
    {
        key = 'machete',
        label = 'Machete Forging',
        description = 'Kowalstwo i bron biala.',
        group = 'Blacksmith',
        tier = 1,
        position = { x = 80, y = 52 },
        skill = 'blacksmith',
        cost = 1,
        recipeKeys = { 'machete' },
    },
}
